[2024-11-28T09:57:45.995+0000] {processor.py:157} INFO - Started process (PID=15089) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:45.995+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:57:45.996+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:57:45.995+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:45.998+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:46.004+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.012 seconds
[2024-11-28T09:57:49.120+0000] {processor.py:157} INFO - Started process (PID=15110) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:49.121+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:57:49.121+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:57:49.121+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:49.123+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:57:49.123+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 7
    with DAG
            ^
SyntaxError: expected ':'
[2024-11-28T09:57:49.124+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:49.138+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.021 seconds
[2024-11-28T09:57:51.205+0000] {processor.py:157} INFO - Started process (PID=15119) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:51.206+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:57:51.206+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:57:51.206+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:51.208+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:57:51.208+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 7
    with DAG 
             ^
SyntaxError: expected ':'
[2024-11-28T09:57:51.209+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:51.220+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.017 seconds
[2024-11-28T09:57:53.545+0000] {processor.py:157} INFO - Started process (PID=15141) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:53.548+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:57:53.549+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:57:53.549+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:53.556+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:57:53.555+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 7
    with DAG ()
               ^
SyntaxError: expected ':'
[2024-11-28T09:57:53.557+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:53.625+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.083 seconds
[2024-11-28T09:57:54.704+0000] {processor.py:157} INFO - Started process (PID=15156) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:54.705+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:57:54.705+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:57:54.705+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:54.708+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:57:54.707+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 7
    with DAG ('')
                 ^
SyntaxError: expected ':'
[2024-11-28T09:57:54.708+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:54.720+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T09:57:59.485+0000] {processor.py:157} INFO - Started process (PID=15184) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:59.486+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:57:59.486+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:57:59.486+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:59.489+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:57:59.488+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 7
    with DAG ('extract_dag')
                            ^
SyntaxError: expected ':'
[2024-11-28T09:57:59.490+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:57:59.507+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.025 seconds
[2024-11-28T09:58:06.046+0000] {processor.py:157} INFO - Started process (PID=15227) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:06.047+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:58:06.047+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:06.047+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:06.049+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:06.049+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 8
    )
     ^
SyntaxError: expected ':'
[2024-11-28T09:58:06.050+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:06.062+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T09:58:09.617+0000] {processor.py:157} INFO - Started process (PID=15249) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:09.618+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:58:09.618+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:09.618+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:09.620+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:09.620+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 8
    schedule)
             ^
SyntaxError: expected ':'
[2024-11-28T09:58:09.621+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:09.632+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.017 seconds
[2024-11-28T09:58:14.606+0000] {processor.py:157} INFO - Started process (PID=15290) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:14.606+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:58:14.607+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:14.606+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:14.609+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:14.608+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 8
    schedule = )
               ^
SyntaxError: invalid syntax
[2024-11-28T09:58:14.609+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:14.621+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T09:58:21.013+0000] {processor.py:157} INFO - Started process (PID=15327) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:21.014+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:58:21.015+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:21.014+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:21.017+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:21.016+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 9
    )
     ^
SyntaxError: expected ':'
[2024-11-28T09:58:21.017+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:21.029+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T09:58:26.216+0000] {processor.py:157} INFO - Started process (PID=15364) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:26.216+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:58:26.217+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:26.217+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:26.219+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:26.219+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 9
    starrt)
          ^
SyntaxError: positional argument follows keyword argument
[2024-11-28T09:58:26.220+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:26.232+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T09:58:28.721+0000] {processor.py:157} INFO - Started process (PID=15385) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:28.722+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:58:28.723+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:28.722+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:28.725+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:28.725+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 9
    start)
         ^
SyntaxError: positional argument follows keyword argument
[2024-11-28T09:58:28.726+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:28.750+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.031 seconds
[2024-11-28T09:58:30.895+0000] {processor.py:157} INFO - Started process (PID=15394) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:30.896+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:58:30.896+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:30.896+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:30.898+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:30.898+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 9
    start_date)
              ^
SyntaxError: positional argument follows keyword argument
[2024-11-28T09:58:30.899+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:30.911+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T09:58:33.828+0000] {processor.py:157} INFO - Started process (PID=15421) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:33.829+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:58:33.829+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:33.829+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:33.832+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:33.831+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 9
    start_date = date)
                      ^
SyntaxError: expected ':'
[2024-11-28T09:58:33.833+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:33.848+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.025 seconds
[2024-11-28T09:58:35.204+0000] {processor.py:157} INFO - Started process (PID=15443) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:35.205+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:58:35.205+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:35.205+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:35.208+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:35.207+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 9
    start_date = datetime)
                          ^
SyntaxError: expected ':'
[2024-11-28T09:58:35.208+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:35.224+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.023 seconds
[2024-11-28T09:58:37.781+0000] {processor.py:157} INFO - Started process (PID=15458) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:37.781+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:58:37.782+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:37.782+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:37.784+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:37.784+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 9
    start_date = datetime())
                            ^
SyntaxError: expected ':'
[2024-11-28T09:58:37.784+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:37.796+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T09:58:57.541+0000] {processor.py:157} INFO - Started process (PID=15592) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:57.541+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:58:57.542+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:57.542+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:57.545+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:58:57.544+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 9
    start_date = datetime(2022))
                                ^
SyntaxError: expected ':'
[2024-11-28T09:58:57.546+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:58:57.559+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.020 seconds
[2024-11-28T09:59:00.268+0000] {processor.py:157} INFO - Started process (PID=15613) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:00.269+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:00.271+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:00.270+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:00.273+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:00.272+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 9
    start_date = datetime(2022, 1, 1))
                                      ^
SyntaxError: expected ':'
[2024-11-28T09:59:00.273+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:00.286+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.021 seconds
[2024-11-28T09:59:05.244+0000] {processor.py:157} INFO - Started process (PID=15649) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:05.245+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:05.245+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:05.245+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:05.248+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:05.247+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 10
    )
     ^
SyntaxError: expected ':'
[2024-11-28T09:59:05.248+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:05.260+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T09:59:06.465+0000] {processor.py:157} INFO - Started process (PID=15657) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:06.466+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:06.466+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:06.466+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:06.469+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:06.468+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 11
    )
     ^
SyntaxError: expected ':'
[2024-11-28T09:59:06.469+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:06.491+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.029 seconds
[2024-11-28T09:59:10.344+0000] {processor.py:157} INFO - Started process (PID=15679) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:10.345+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:10.346+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:10.345+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:10.348+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:10.347+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 11
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-11-28T09:59:10.348+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:10.360+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T09:59:15.392+0000] {processor.py:157} INFO - Started process (PID=15715) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:15.393+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:15.393+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:15.393+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:15.396+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:15.396+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 11
    )
     ^
SyntaxError: expected ':'
[2024-11-28T09:59:15.397+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:15.412+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.023 seconds
[2024-11-28T09:59:19.357+0000] {processor.py:157} INFO - Started process (PID=15745) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:19.357+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:19.358+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:19.358+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:19.360+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:19.360+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 11
    ) as 
         ^
SyntaxError: invalid syntax
[2024-11-28T09:59:19.361+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:19.373+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T09:59:23.346+0000] {processor.py:157} INFO - Started process (PID=15773) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:23.347+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:23.347+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:23.347+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:23.350+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:23.349+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12
    
    ^
IndentationError: expected an indented block after 'with' statement on line 7
[2024-11-28T09:59:23.350+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:23.362+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T09:59:29.526+0000] {processor.py:157} INFO - Started process (PID=15817) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:29.527+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:29.532+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:29.532+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:29.539+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:29.537+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract
NameError: name 'extract' is not defined
[2024-11-28T09:59:29.541+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:29.553+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.030 seconds
[2024-11-28T09:59:32.721+0000] {processor.py:157} INFO - Started process (PID=15839) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:32.722+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:32.723+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:32.723+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:32.736+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:32.729+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task
NameError: name 'extract_task' is not defined
[2024-11-28T09:59:32.742+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:32.773+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.055 seconds
[2024-11-28T09:59:36.637+0000] {processor.py:157} INFO - Started process (PID=15867) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:36.638+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:36.638+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:36.638+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:36.642+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:36.641+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task = Bas
NameError: name 'Bas' is not defined
[2024-11-28T09:59:36.642+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:36.655+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.020 seconds
[2024-11-28T09:59:37.781+0000] {processor.py:157} INFO - Started process (PID=15869) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:37.782+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:37.783+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:37.783+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:37.791+0000] {processor.py:836} INFO - DAG(s) dict_keys(['extract_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:37.907+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:37.907+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:extract_dag
[2024-11-28T09:59:37.921+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:37.921+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:extract_dag
[2024-11-28T09:59:37.929+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:37.929+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:extract_dag
[2024-11-28T09:59:37.944+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:37.943+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-11-28T09:59:37.951+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:37.951+0000] {dag.py:2763} INFO - Creating ORM DAG for extract_dag
[2024-11-28T09:59:37.957+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:37.957+0000] {dag.py:3504} INFO - Setting next_dagrun for extract_dag to None, run_after=None
[2024-11-28T09:59:37.976+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.197 seconds
[2024-11-28T09:59:41.681+0000] {processor.py:157} INFO - Started process (PID=15897) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:41.682+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:41.682+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:41.682+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:41.686+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:41.685+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task = BashOperator(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2024-11-28T09:59:41.686+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:41.699+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.020 seconds
[2024-11-28T09:59:44.637+0000] {processor.py:157} INFO - Started process (PID=15932) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:44.638+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:44.639+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:44.638+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:44.643+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:44.642+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 13, in <module>
    task
NameError: name 'task' is not defined
[2024-11-28T09:59:44.644+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:44.657+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.022 seconds
[2024-11-28T09:59:46.872+0000] {processor.py:157} INFO - Started process (PID=15942) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:46.873+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:46.873+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:46.873+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:46.880+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:46.876+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 13, in <module>
    task_id
NameError: name 'task_id' is not defined
[2024-11-28T09:59:46.883+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:46.897+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.027 seconds
[2024-11-28T09:59:52.841+0000] {processor.py:157} INFO - Started process (PID=15971) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:52.842+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:52.842+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:52.842+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:52.846+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:52.845+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task = BashOperator(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2024-11-28T09:59:52.846+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:52.859+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.020 seconds
[2024-11-28T09:59:55.859+0000] {processor.py:157} INFO - Started process (PID=16004) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:55.860+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:55.860+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:55.860+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:55.864+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:55.863+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task = BashOperator(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2024-11-28T09:59:55.864+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:55.877+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.020 seconds
[2024-11-28T09:59:58.065+0000] {processor.py:157} INFO - Started process (PID=16019) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:58.066+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T09:59:58.066+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:58.066+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:58.068+0000] {logging_mixin.py:150} INFO - [2024-11-28T09:59:58.068+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 15
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-11-28T09:59:58.069+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T09:59:58.081+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T10:00:00.936+0000] {processor.py:157} INFO - Started process (PID=16034) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:00.937+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:00:00.938+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:00:00.937+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:00.940+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:00:00.939+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 15
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-11-28T10:00:00.940+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:00.953+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.018 seconds
[2024-11-28T10:00:03.137+0000] {processor.py:157} INFO - Started process (PID=16049) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:03.138+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:00:03.139+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:00:03.139+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:03.143+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:00:03.142+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 15
    )
    ^
SyntaxError: invalid syntax
[2024-11-28T10:00:03.143+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:03.174+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.040 seconds
[2024-11-28T10:00:03.813+0000] {processor.py:157} INFO - Started process (PID=16056) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:03.814+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:00:03.814+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:00:03.814+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:03.818+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:00:03.817+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task = BashOperator(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2024-11-28T10:00:03.819+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:03.832+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.021 seconds
[2024-11-28T10:00:34.114+0000] {processor.py:157} INFO - Started process (PID=16235) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:34.115+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:00:34.116+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:00:34.116+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:34.119+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:00:34.118+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task = BashOperator(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2024-11-28T10:00:34.119+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:00:34.131+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.019 seconds
[2024-11-28T10:01:04.419+0000] {processor.py:157} INFO - Started process (PID=16401) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:01:04.421+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:01:04.422+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:01:04.421+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:01:04.426+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:01:04.424+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task = BashOperator(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2024-11-28T10:01:04.426+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:01:04.443+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.027 seconds
[2024-11-28T10:01:32.798+0000] {processor.py:157} INFO - Started process (PID=16580) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:01:32.799+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:01:32.799+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:01:32.799+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:01:32.803+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:01:32.802+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task = BashOperator(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2024-11-28T10:01:32.803+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:01:32.815+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.019 seconds
[2024-11-28T10:01:54.878+0000] {processor.py:157} INFO - Started process (PID=16717) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:01:54.879+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:01:54.879+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:01:54.879+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:01:54.883+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:01:54.882+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task = BashOperator(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2024-11-28T10:01:54.883+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:01:54.895+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.020 seconds
[2024-11-28T10:02:25.178+0000] {processor.py:157} INFO - Started process (PID=17002) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:02:25.179+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:02:25.180+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:02:25.180+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:02:25.184+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:02:25.183+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task = BashOperator(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2024-11-28T10:02:25.184+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:02:25.196+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.020 seconds
[2024-11-28T10:02:55.473+0000] {processor.py:157} INFO - Started process (PID=17304) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:02:55.474+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:02:55.475+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:02:55.474+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:02:55.478+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:02:55.477+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py", line 12, in <module>
    extract_task = BashOperator(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 412, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2024-11-28T10:02:55.478+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:02:55.489+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.019 seconds
[2024-11-28T10:03:02.675+0000] {processor.py:157} INFO - Started process (PID=17349) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:03:02.676+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:03:02.676+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:03:02.676+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:03:02.684+0000] {processor.py:836} INFO - DAG(s) dict_keys(['extract_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:03:02.788+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:03:02.788+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-11-28T10:03:02.800+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:03:02.800+0000] {dag.py:3504} INFO - Setting next_dagrun for extract_dag to None, run_after=None
[2024-11-28T10:03:02.818+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.145 seconds
[2024-11-28T10:03:03.922+0000] {processor.py:157} INFO - Started process (PID=17357) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:03:03.923+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:03:03.924+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:03:03.923+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:03:03.931+0000] {processor.py:836} INFO - DAG(s) dict_keys(['extract_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:03:03.937+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:03:03.936+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-11-28T10:03:03.952+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:03:03.952+0000] {dag.py:3504} INFO - Setting next_dagrun for extract_dag to None, run_after=None
[2024-11-28T10:03:03.967+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.047 seconds
[2024-11-28T10:03:34.979+0000] {processor.py:157} INFO - Started process (PID=17613) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:03:34.980+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:03:34.980+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:03:34.980+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:03:34.987+0000] {processor.py:836} INFO - DAG(s) dict_keys(['extract_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:03:35.006+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:03:35.006+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-11-28T10:03:35.019+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:03:35.019+0000] {dag.py:3504} INFO - Setting next_dagrun for extract_dag to None, run_after=None
[2024-11-28T10:03:35.033+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.056 seconds
[2024-11-28T10:04:05.164+0000] {processor.py:157} INFO - Started process (PID=17796) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:04:05.164+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:04:05.165+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:04:05.165+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:04:05.173+0000] {processor.py:836} INFO - DAG(s) dict_keys(['extract_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:04:05.189+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:04:05.188+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-11-28T10:04:05.202+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:04:05.201+0000] {dag.py:3504} INFO - Setting next_dagrun for extract_dag to None, run_after=None
[2024-11-28T10:04:05.217+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.055 seconds
[2024-11-28T10:04:35.371+0000] {processor.py:157} INFO - Started process (PID=17993) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:04:35.371+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:04:35.372+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:04:35.372+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:04:35.379+0000] {processor.py:836} INFO - DAG(s) dict_keys(['extract_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:04:35.395+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:04:35.395+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-11-28T10:04:35.408+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:04:35.408+0000] {dag.py:3504} INFO - Setting next_dagrun for extract_dag to None, run_after=None
[2024-11-28T10:04:35.422+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.053 seconds
[2024-11-28T10:05:05.626+0000] {processor.py:157} INFO - Started process (PID=18238) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:05:05.627+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py for tasks to queue
[2024-11-28T10:05:05.627+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:05:05.627+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:05:05.634+0000] {processor.py:836} INFO - DAG(s) dict_keys(['extract_dag']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py
[2024-11-28T10:05:05.650+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:05:05.650+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2024-11-28T10:05:05.664+0000] {logging_mixin.py:150} INFO - [2024-11-28T10:05:05.664+0000] {dag.py:3504} INFO - Setting next_dagrun for extract_dag to None, run_after=None
[2024-11-28T10:05:05.680+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract_dag.py took 0.057 seconds
